- name: Verify and ensure OSPF configuration on all L3 devices
  hosts: routers
  gather_facts: false
  tags: ospf

  tasks:
    - name: Check OSPF process is running
      cisco.ios.ios_command:
        commands: show ip ospf
      register: ospf_proc
      failed_when: "'OSPF Router' not in ospf_proc.stdout[0]"

    - name: Show OSPF neighbor table
      cisco.ios.ios_command:
        commands: show ip ospf neighbor
      register: ospf_nbrs

    - name: Display OSPF neighbors
      ansible builtin.debug:
        msg: "{{ ospf_nbrs.stdout_lines }}"
